In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


# extract zip file

In [ ]:
!pip install -U --no-cache-dir gdown --pre

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Attempting uninstall: gdown
    Found existing installation: gdown 4.4.0
    Uninstalling gdown-4.4.0:
      Successfully uninstalled gdown-4.4.0


In [ ]:
%cd /content/drive/MyDrive/Alpaco_NLP

/content/drive/MyDrive/Alpaco_NLP


In [ ]:
!pwd

/content/drive/MyDrive/Alpaco_NLP


In [ ]:
!gdown '1kvkYZvejEjIrrcn3MclW1bwTyaflYzSv'

Downloading...
From: https://drive.google.com/uc?id=1kvkYZvejEjIrrcn3MclW1bwTyaflYzSv
To: /content/drive/MyDrive/Alpaco_NLP/TL1.zip
100% 227M/227M [00:10<00:00, 21.6MB/s]


In [ ]:
import zipfile

path_to_zip_file1 = '/content/drive/MyDrive/Alpaco_NLP/TL1.zip'
directory_to_extract_to = '/content/drive/MyDrive/Alpaco_NLP/training/tl1'

with zipfile.ZipFile(path_to_zip_file1, 'r') as zip_ref:
    zip_ref.extractall(directory_to_extract_to)

In [ ]:
!gdown 1vgbM7FAyZU5y5CBgv8Gv9UAVa9KUWraq # VL1

Downloading...
From: https://drive.google.com/uc?id=1vgbM7FAyZU5y5CBgv8Gv9UAVa9KUWraq
To: /content/drive/MyDrive/Alpaco_NLP/VL1.zip
100% 28.3M/28.3M [00:00<00:00, 40.0MB/s]


In [ ]:
import zipfile

path_to_zip_file1 = '/content/drive/MyDrive/Alpaco_NLP/VL1.zip'
directory_to_extract_to = '/content/drive/MyDrive/Alpaco_NLP/validation/vl1'

with zipfile.ZipFile(path_to_zip_file1, 'r') as zip_ref:
    zip_ref.extractall(directory_to_extract_to)

# json to dataframe to pickle




In [ ]:
import json
import os
import glob
import pandas as pd
from tqdm import tqdm

train_json_path = '/content/drive/MyDrive/Alpaco_NLP/training/tl1/'
dict_train_json_folder = []

df_train = pd.DataFrame()

for dir in os.listdir(train_json_path):
    dict_train_json_folder.append(dir)
    break

for dict_key in dict_train_json_folder:
    for file in tqdm(glob.glob(train_json_path + dict_key + '/20per/*.json')):
        with open(file, "r") as json_file:
            json_data = json.load(json_file)
            original = json_data["Meta(Refine)"]["passage"]
            summary1 = json_data["Annotation"]["summary1"]
            df_train = df_train.append({"original": original, "summary": summary1}, ignore_index=True)
    for file in tqdm(glob.glob(train_json_path + dict_key + '/2~3sent/*.json')):
        with open(file, "r") as json_file:
            json_data = json.load(json_file)
            original = json_data["Meta(Refine)"]["passage"]
            summary1 = json_data["Annotation"]["summary1"]
            df_train = df_train.append({"original": original, "summary": summary1}, ignore_index=True)
len(df_train)

146771

In [ ]:
import json
import os
import glob
import pandas as pd
from tqdm import tqdm

train_json_path = '/content/drive/MyDrive/Alpaco_NLP/training/tl1/'
dict_train_json_folder = []

df_train = pd.DataFrame()

for dir in os.listdir(train_json_path):
    dict_train_json_folder.append(dir)
    break

for dict_key in dict_train_json_folder:
    for file in tqdm(glob.glob(train_json_path + dict_key + '/20per/*.json')):
        with open(file, "r") as json_file:
            json_data = json.load(json_file)
            original = json_data["Meta(Refine)"]["passage"]
            summary1 = json_data["Annotation"]["summary1"]
            df_train = df_train.append({"original": original, "summary": summary1}, ignore_index=True)
    for file in tqdm(glob.glob(train_json_path + dict_key + '/2~3sent/*.json')):
        with open(file, "r") as json_file:
            json_data = json.load(json_file)
            original = json_data["Meta(Refine)"]["passage"]
            summary1 = json_data["Annotation"]["summary1"]
            df_train = df_train.append({"original": original, "summary": summary1}, ignore_index=True)
len(df_train)

100%|██████████| 10800/10800 [00:54<00:00, 196.66it/s]


21600

In [ ]:
len(df_train)


21600

In [ ]:
df_train.to_pickle('/content/drive/MyDrive/Alpaco_NLP/training/tl_news.pkl')

In [ ]:
import json
import os
import glob
import pandas as pd
from tqdm import tqdm

train_json_path = '/content/drive/MyDrive/Alpaco_NLP/validation/vl1/'
dict_train_json_folder = []

df_test = pd.DataFrame()

for dir in os.listdir(train_json_path):
    dict_train_json_folder.append(dir)
    break

for dict_key in dict_train_json_folder:
    for file in tqdm(glob.glob(train_json_path + dict_key + '/20per/*.json')):
        with open(file, "r") as json_file:
            json_data = json.load(json_file)
            original = json_data["Meta(Refine)"]["passage"]
            summary1 = json_data["Annotation"]["summary1"]
            df_test = df_test.append({"original": original, "summary": summary1}, ignore_index=True)
    for file in tqdm(glob.glob(train_json_path + dict_key + '/2~3sent/*.json')):
        with open(file, "r") as json_file:
            json_data = json.load(json_file)
            original = json_data["Meta(Refine)"]["passage"]
            summary1 = json_data["Annotation"]["summary1"]
            df_test = df_test.append({"original": original, "summary": summary1}, ignore_index=True)
len(df_test)

100%|██████████| 1350/1350 [00:19<00:00, 69.30it/s] 


2700

In [ ]:
df_test.to_pickle('/content/drive/MyDrive/Alpaco_NLP/validation/vl_news.pkl')

# load pickle


In [ ]:
!pwd

/Users/jeonminjeong


In [ ]:
import pickle

with open('/content/drive/MyDrive/mjjeon/tl_news.pkl', 'rb') as f:
    df_train = pickle.load(f)

with open('/content/drive/MyDrive/mjjeon/vl_news.pkl', 'rb') as f:
    df_test = pickle.load(f)

In [ ]:
import pickle

with open('/content/drive/MyDrive/Alpaco_NLP/training/tl_news.pkl', 'rb') as f:
    df_train = pickle.load(f)

with open('/content/drive/MyDrive/Alpaco_NLP/validation/vl_news.pkl', 'rb') as f:
    df_test = pickle.load(f)

In [ ]:
len(df_train), len(df_test)

(21600, 2700)

# load transformer

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.8 MB 26.4 MB/s 
     |████████████████████████████████| 7.6 MB 82.1 MB/s 
     |████████████████████████████████| 182 kB 105.7 MB/s 


# 이건 안된다

In [ ]:
from transformers import BartTokenizer, TFBartForConditionalGeneration
import tensorflow as tf

tokenizer = BartTokenizer.from_pretrained("gogamza/kobart-base-v2", model_max_length = 256)
model = TFBartForConditionalGeneration.from_pretrained("gogamza/kobart-base-v2", from_pt = True)

You passed along `num_labels=3` with an incompatible id to label map: {'0': 'NEGATIVE', '1': 'POSITIVE'}. The number of labels wil be overwritten to 2.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'PreTrainedTokenizerFast'. 
The class this function is called from is 'BartTokenizer'.
You passed along `num_labels=3` with an incompatible id to label map: {'0': 'NEGATIVE', '1': 'POSITIVE'}. The number of labels wil be overwritten to 2.
Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBartForConditionalGeneration: ['decoder.embed_tokens.weight', 'encoder.embed_tokens.weight']
- This IS expected if you are initializing TFBartForConditionalGeneration from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertFor

In [ ]:
from transformers import AutoConfig
config = AutoConfig.from_pretrained("gogamza/kobart-base-v2")
config

You passed along `num_labels=3` with an incompatible id to label map: {'0': 'NEGATIVE', '1': 'POSITIVE'}. The number of labels wil be overwritten to 2.


BartConfig {
  "_name_or_path": "gogamza/kobart-base-v2",
  "activation_dropout": 0.0,
  "activation_function": "gelu",
  "add_bias_logits": false,
  "add_final_layer_norm": false,
  "architectures": [
    "BartModel"
  ],
  "attention_dropout": 0.0,
  "author": "Heewon Jeon(madjakarta@gmail.com)",
  "bos_token_id": 1,
  "classif_dropout": 0.1,
  "classifier_dropout": 0.1,
  "d_model": 768,
  "decoder_attention_heads": 16,
  "decoder_ffn_dim": 3072,
  "decoder_layerdrop": 0.0,
  "decoder_layers": 6,
  "decoder_start_token_id": 1,
  "do_blenderbot_90_layernorm": false,
  "dropout": 0.1,
  "encoder_attention_heads": 16,
  "encoder_ffn_dim": 3072,
  "encoder_layerdrop": 0.0,
  "encoder_layers": 6,
  "eos_token_id": 1,
  "extra_pos_embeddings": 2,
  "force_bos_token_to_be_generated": false,
  "forced_eos_token_id": 1,
  "gradient_checkpointing": false,
  "id2label": {
    "0": "NEGATIVE",
    "1": "POSITIVE"
  },
  "init_std": 0.02,
  "is_encoder_decoder": true,
  "kobart_version": 2.0,
  

# 이건된다

In [ ]:
from transformers import PreTrainedTokenizerFast, TFBartForConditionalGeneration
import tensorflow as tf

tokenizer = PreTrainedTokenizerFast.from_pretrained("digit82/kobart-summarization", model_max_length=256)
model = TFBartForConditionalGeneration.from_pretrained("digit82/kobart-summarization", from_pt = True)

You passed along `num_labels=3` with an incompatible id to label map: {'0': 'NEGATIVE', '1': 'POSITIVE'}. The number of labels wil be overwritten to 2.
Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBartForConditionalGeneration: ['model.decoder.embed_tokens.weight', 'model.encoder.embed_tokens.weight']
- This IS expected if you are initializing TFBartForConditionalGeneration from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBartForConditionalGeneration from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBartForConditionalGeneration were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you

In [ ]:

text = """
1일 오후 9시까지 최소 20만3220명이 코로나19에 신규 확진됐다. 또다시 동시간대 최다 기록으로, 사상 처음 20만명대에 진입했다.
방역 당국과 서울시 등 각 지방자치단체에 따르면 이날 0시부터 오후 9시까지 전국 신규 확진자는 총 20만3220명으로 집계됐다.
국내 신규 확진자 수가 20만명대를 넘어선 것은 이번이 처음이다.
동시간대 최다 기록은 지난 23일 오후 9시 기준 16만1389명이었는데, 이를 무려 4만1831명이나 웃돌았다. 전날 같은 시간 기록한 13만3481명보다도 6만9739명 많다.
확진자 폭증은 3시간 전인 오후 6시 집계에서도 예견됐다.
오후 6시까지 최소 17만8603명이 신규 확진돼 동시간대 최다 기록(24일 13만8419명)을 갈아치운 데 이어 이미 직전 0시 기준 역대 최다 기록도 넘어섰다. 역대 최다 기록은 지난 23일 0시 기준 17만1451명이었다.
17개 지자체별로 보면 서울 4만6938명, 경기 6만7322명, 인천 1만985명 등 수도권이 12만5245명으로 전체의 61.6%를 차지했다. 서울과 경기는 모두 동시간대 기준 최다로, 처음으로 각각 4만명과 6만명을 넘어섰다.
비수도권에서는 7만7975명(38.3%)이 발생했다. 제주를 제외한 나머지 지역에서 모두 동시간대 최다를 새로 썼다.
부산 1만890명, 경남 9909명, 대구 6900명, 경북 6977명, 충남 5900명, 대전 5292명, 전북 5150명, 울산 5141명, 광주 5130명, 전남 4996명, 강원 4932명, 충북 3845명, 제주 1513명, 세종 1400명이다.
집계를 마감하는 자정까지 시간이 남아있는 만큼 2일 0시 기준으로 발표될 신규 확진자 수는 이보다 더 늘어날 수 있다. 이에 따라 최종 집계되는 확진자 수는 21만명 안팎을 기록할 수 있을 전망이다.
한편 전날 하루 선별진료소에서 이뤄진 검사는 70만8763건으로 검사 양성률은 40.5%다. 양성률이 40%를 넘은 것은 이번이 처음이다. 확산세가 계속 거세질 수 있다는 얘기다.
이날 0시 기준 신규 확진자는 13만8993명이었다. 이틀 연속 13만명대를 이어갔다.
"""
text2 = """
안녕 명탐정 코난의 이야기를 시작하도록 하지. 내 이름은 에도가와 코난, 탐정이지. 나는 원래 쿠도 신이치라는 고등학생 탐정이었지만,
란과 유원지에 놀러갔다가 검은 조직의 거래 현장을 목격 후 뒤에서 오는 다른 조직원을 보지 못한 채 습격을 당했다.
그 조직원은 이상한 약을 나에게 먹였고, 경찰에 발견된 나는 초등학생으로 몸이 작아져 있었다.
현재는 소년 탐정단에서 겐타, 미츠히코, 아유미와 활동하고 있고, 최근에는 하이바라 아이라는 이전 조직원 약 개발자를 만나게 되었다.
"""
text = text2.replace('\n', ' ')

raw_input_ids = tokenizer.encode(text)
input_ids1 = [tokenizer.bos_token_id] + raw_input_ids + [tokenizer.eos_token_id]

summary_ids = model.generate([input_ids1],  num_beams=4,  max_length=512,  eos_token_id=1)
tokenizer.decode(np.array(summary_ids).squeeze().tolist(), skip_special_tokens=True)

'에도도 신이치라는 고등학생 탐정이었지만, 란과 유원지에 놀러갔다가 검은 조직의 거래 현장을 목격 후 뒤에서 오는 다른 조직원을 보지 못한 채 습격을 당했고, 그 조직원은 이상한 약을 나에게 먹였고, 경찰에 발견된 나는 초등학생으로 몸이 작아져 현재는 소년 탐정단에서 겐타, 미츠히코, 아유미와 활동하고 있고, 최근에는 하이바라 아이라는 이전 조직원 약 개발자를 만나게 되었다.'

In [ ]:
torch.tensor([input_ids1]).shape

torch.Size([1, 117])

# load dataset

In [ ]:
X_train_list = df_train['original'].tolist()
X_test_list = df_test['original'].tolist()
y_train = df_train['summary'].tolist()
y_test = df_test['summary'].tolist()

In [ ]:
print(tokenizer.model_max_length)

256


In [ ]:
X_train = tokenizer(X_train_list, truncation=True, padding=True)
X_test = tokenizer(X_test_list, truncation=True, padding=True)

In [ ]:
Y_train = tokenizer(y_train, truncation=True, padding=True)
Y_test = tokenizer(y_test, truncation=True, padding=True)

In [ ]:
X_train

In [ ]:
print(X_train[0].tokens)
print(X_train[0].ids)

['▁8일', '▁인천', '▁영', '종', '도', '▁스카', '이', '72', '▁골프', '앤', '리조', '트', '▁오', '션', '▁코스', '.\n', '▁', '▁한국', '▁여자', '프로', '골프', '(K', 'L', 'PG', 'A)', '▁투어', '▁하나금융', '그룹', '▁챔피언십', '▁최종', '▁라', '운드', '에', '▁나선', '▁선수', '▁62', '명은', '▁초', '속', '▁7', 'm', '▁찬', '바람', '을', '▁맞', '으며', '▁추', '위와', '▁싸', '웠다.\n', '▁', '▁핀', '에', '▁꽂', '힌', '▁깃', '대는', '▁심하게', '▁흔들', '렸다.\n', '▁', '▁선수들은', '▁두', '꺼', '운', '▁점', '퍼', '를', '▁입고', '▁벗', '기를', '▁반복', '했다.\n', '▁', '▁세계', '▁1위', '▁고', '진', '영', '(25', ')과', '▁장', '타자', '▁김', '아', '림', '(25', ')은', '▁방한', '용', '▁귀', '마', '개', '까지', '▁착용', '했다.\n', '▁', '▁강', '풍', '▁탓에', '▁이날', '▁언', '더', '파를', '▁기록한', '▁선수는', '▁3명', '뿐', '이었다.\n', '▁', '▁안', '나', '린', '(25', ')은', '▁그중', '에서도', '▁가장', '▁돋보', '였다.\n', '▁', '▁공동', '▁선두', '로', '▁출발', '한', '▁그는', '▁최종', '▁라', '운드', '에서', '▁버디', '▁2개', ',', '▁보기', '▁1', '개로', '▁1', '타를', '▁줄', '였다.\n', '▁', '▁합', '계', '▁8', '언더파', '.\n', '▁', '▁장', '하나', '(28', '·', '5', '언더파', ')를', '▁3', '타', '▁차로', '▁따돌', '리고', '▁우

In [ ]:
import tensorflow as tf

# 주어진 데이터소스를 여러 Tensor로 자른 후 iterator(반복가능 객체)로 만들기
train_dataset = tf.data.Dataset.from_tensor_slices((
    dict(X_train),
    Y_train
))

val_dataset = tf.data.Dataset.from_tensor_slices((
    dict(X_test),
    Y_test
))

In [ ]:
train_dataset = tf.data.Dataset.from_tensor_slices(train_dataset_dict)

In [ ]:
train_dataset.take(1)

<TakeDataset element_spec={'input_ids': TensorSpec(shape=(256,), dtype=tf.int64, name=None), 'decoder_input_ids': TensorSpec(shape=(256,), dtype=tf.int64, name=None), 'labels': TensorSpec(shape=(256,), dtype=tf.int64, name=None)}>

In [ ]:
import numpy as np
import torch


max_len = 256
pad_index = tokenizer.pad_token_id
ignore_index = -100

def add_padding_data(inputs):
    if len(inputs) < max_len:
        pad = np.array([pad_index] *(max_len - len(inputs)))
        inputs = np.concatenate([inputs, pad])
    else:
        inputs = inputs[:max_len]

    return inputs

def add_ignored_data(inputs):
    if len(inputs) < max_len:
        pad = np.array([pad_index] *(max_len - len(inputs)))
        inputs = np.concatenate([inputs, pad])
    else:
        inputs = inputs[:max_len]

    return inputs

def translateData(df_train):
    
    input_ids_list, dec_input_ids_list, label_ids_list = [], [], []
    for idx in tqdm(range(len(df_train))):
        instance = df_train.iloc[idx]
        input_ids = tokenizer.encode(instance['original'])
        input_ids = add_padding_data(input_ids)

        label_ids = tokenizer.encode(instance['summary'])
        label_ids.append(tokenizer.eos_token_id)
        dec_input_ids = [tokenizer.eos_token_id]
        dec_input_ids += label_ids[:-1]
        dec_input_ids = add_padding_data(dec_input_ids)
        label_ids = add_ignored_data(label_ids)

        input_ids_list.append(input_ids)
        dec_input_ids_list.append(dec_input_ids)
        label_ids_list.append(label_ids)
    print(len(input_ids_list), len(dec_input_ids_list), len(label_ids_list))

    return input_ids_list, dec_input_ids_list, label_ids_list
'''
    input_ids_tensor = torch.tensor(np.array(input_ids_list)).reshape(1, -1)
    decoder_input_ids_tensor = torch.tensor(np.array(dec_input_ids_list)).reshape(1, -1)
    labels_tensor = torch.tensor(np.array(label_ids_list)).reshape(1, -1)

    return_dict = {'input_ids': input_ids_tensor,
            'decoder_input_ids': decoder_input_ids_tensor,
            'labels': labels_tensor}

    return return_dict
'''
input_ids_list, dec_input_ids_list, label_ids_list = translateData(df_train)

# train_dataset_dict['input_ids'][0], train_dataset_dict['decoder_input_ids'][0], train_dataset_dict['labels'][0]

100%|██████████| 21600/21600 [00:41<00:00, 515.51it/s]

21600 21600 21600


In [ ]:
len(input_ids_list), len(dec_input_ids_list), len(label_ids_list)

(21600, 21600, 21600)

In [ ]:
train_dataset_dict['input_ids'] = torch.tensor(np.array(input_ids_list))
train_dataset_dict['decoder_input_ids'] = torch.tensor(np.array(dec_input_ids_list))
train_dataset_dict['labels'] = torch.tensor(np.array(label_ids_list))
train_dataset_dict.keys()

dict_keys(['input_ids', 'decoder_input_ids', 'labels'])

In [ ]:
train_dataset_dict['input_ids'].shape

torch.Size([21600, 256])

In [ ]:
with open('/content/drive/MyDrive/mjjeon/train_dataset.pickle', 'wb') as handle:
    pickle.dump(train_dataset_dict, handle)

In [ ]:
train_dataset = {}
train_dataset['input_ids'] = np.array(input_ids_list)
train_dataset['decoder_input_ids'] = np.array(dec_input_ids_list)
train_dataset['labels'] = np.array(label_ids_list)


1

In [ ]:
model.summary() 

Model: "tf_bart_for_conditional_generation"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 model (TFBartMainLayer)     multiple                  123859968 
                                                                 
 final_logits_bias (BiasLaye  multiple                 30000     
 r)                                                              
                                                                 
Total params: 123,889,968
Trainable params: 123,859,968
Non-trainable params: 30,000
_________________________________________________________________


In [ ]:
optimizer = tf.keras.optimizers.Adam(learning_rate=5e-5)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)

In [ ]:
model.compile(optimizer=optimizer, loss=loss, metrics=['accuracy'])

In [ ]:
list(train_dataset.take(1))

In [ ]:
batch_size = 32
steps = len(df_train) // batch_size + 1
print(steps)
adam = tf.keras.optimizers.Adam(learning_rate=3e-5, epsilon=1e-08)

676


In [ ]:
train_dataset.take(1)

<TakeDataset element_spec={'input_ids': TensorSpec(shape=(256,), dtype=tf.int32, name=None), 'decoder_input_ids': TensorSpec(shape=(256,), dtype=tf.int32, name=None), 'labels': TensorSpec(shape=(256,), dtype=tf.int32, name=None)}>

In [ ]:
for input_ids in train_dataset.take(1):  # only take first element of dataset
    input_ids_one = input_ids

t_tensor = torch.tensor(list(input_ids_one['input_ids'].numpy()))
len(t_tensor)

256

In [ ]:
t_tensor = t_tensor.reshape(1,-1)

In [ ]:
summary_ids = model.generate(t_tensor,  num_beams=4,  max_length=512,  eos_token_id=1)
tokenizer.decode(np.array(summary_ids).squeeze().tolist(), skip_special_tokens=True)

'8일 한국 영종도 스카이72 골프앤리조트 오션 코스에서 열린 한국 여자프로골프 투어 하나금융그룹 챔피언십 최종 라운드에 나선 선수 62명은 초속 7m 찬바람을 맞으며 초속 7m 찬바람을 맞으며 추위와 싸우고 있다.'

In [ ]:
from tqdm import tqdm

EPOCHS = 5

for epoch in range(EPOCHS):
  epoch_loss = 0

  for input_ids, dec_input_ids, labels in zip(tqdm(train_dataset['input_ids']), train_dataset['decoder_input_ids'], train_dataset['labels']):
      with tf.GradientTape() as tape:

        attention_mask = input_ids.ne(tokenizer.pad_token_id).float()
        decoder_attention_mask = dec_input_ids.ne(tokenizer.pad_token_id).float()

        result = model(input_ids=input_ids,
                        attention_mask=attention_mask,
                        decoder_input_ids=dec_input_ids,
                        decoder_attention_mask=decoder_attention_mask,
                        labels=labels, return_dict=True)
        loss = result[0]
        batch_loss = tf.reduce_mean(loss)
          
      grads = tape.gradient(batch_loss, model.trainable_variables)
      adam.apply_gradients(zip(grads, model.trainable_variables))
      epoch_loss += batch_loss / steps

  print('[Epoch: {:>4}] cost = {:>.9}'.format(epoch + 1, epoch_loss))

TypeError: ignored

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

callback_earlystop = EarlyStopping(
    monitor="val_accuracy", 
    min_delta=0.001,
    patience=2)
checkpoint_filepath = '/content/drive/MyDrive/mjjeon/weights2/'
model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_filepath,
    save_weights_only=True,
    monitor='val_accuracy',
    save_best_only=True)

model.fit(
    train_dataset.shuffle(10000).batch(32), epochs=1, batch_size=32,
    validation_data = val_dataset.shuffle(10000).batch(32),
    callbacks = [callback_earlystop, model_checkpoint_callback]
)

TypeError: ignored

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

callback_earlystop = EarlyStopping(
    monitor="val_accuracy", 
    min_delta=0.001,
    patience=2)
checkpoint_filepath = '/content/drive/MyDrive/mjjeon'
model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_filepath,
    save_weights_only=True,
    monitor='val_accuracy',
    save_best_only=True)
model.fit(
    train_dataset.shuffle(10000).batch(32), epochs=1, batch_size=32,
    validation_data = val_dataset.shuffle(10000).batch(32),
    callbacks = [callback_earlystop, model_checkpoint_callback]
)

ValueError: ignored

In [ ]:
model.save_weights('/content/drive/MyDrive/mjjeon/weights/')

In [ ]:
model.save('/content/drive/MyDrive/mjjeon/v2_saveformat.h5',save_format='tf')

NotImplementedError: ignored

In [ ]:
from transformers import BartTokenizer, TFBartModel
import tensorflow as tf

tokenizer = BartTokenizer.from_pretrained("gogamza/kobart-base-v2")
model = TFBartModel.from_pretrained("gogamza/kobart-base-v2", from_pt = True)

inputs = tokenizer("Hello, my dog is cute", return_tensors="tf")
outputs = model(inputs)

last_hidden_states = outputs.last_hidden_state

You passed along `num_labels=3` with an incompatible id to label map: {'0': 'NEGATIVE', '1': 'POSITIVE'}. The number of labels wil be overwritten to 2.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'PreTrainedTokenizerFast'. 
The class this function is called from is 'BartTokenizer'.
You passed along `num_labels=3` with an incompatible id to label map: {'0': 'NEGATIVE', '1': 'POSITIVE'}. The number of labels wil be overwritten to 2.
Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBartModel: ['decoder.embed_tokens.weight', 'encoder.embed_tokens.weight']
- This IS expected if you are initializing TFBartModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expe

In [ ]:
inputs

{'input_ids': <tf.Tensor: shape=(1, 18), dtype=int32, numpy=
array([[    0,   271, 16997, 20858,   243,   461,   308,   320,   461,
          299, 25873,   461, 15868,   461,   298, 23124,   300,     1]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 18), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
      dtype=int32)>}

In [ ]:
ARTICLE_TO_SUMMARIZE = (
    "안녕하세요 오늘 아침을 책임질 7시 기상 알람입니다. 저는 매일 7시에 알람이 맞춰져 있으며 사용자마다 커스텀이 가능합니다."
    "명탐정 코난은 뛰어난 애니메이션입니다. 28년동안 코난은 어린아이의 몸에 갖혀져 있으면서 기술은 진보하는 것을 보고 있었기 때문입니다."
)
inputs = tokenizer([ARTICLE_TO_SUMMARIZE], max_length=1024, return_tensors="pt", truncation=True)

# Generate Summary
summary_ids = model.generate(inputs["input_ids"], num_beams=2, min_length=0, max_length=20)
# tokenizer.batch_decode(summary_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
summary_ids

<tf.Tensor: shape=(1, 20), dtype=int32, numpy=
array([[  1,   0, 416,   5,   5, 415,   5,   5, 461,   5,   5, 461, 416,
          5,   5, 416,   5,   5, 461,   1]], dtype=int32)>

In [ ]:
tokenizer.vocab_files_names

{'vocab_file': 'vocab.json', 'merges_file': 'merges.txt'}

In [ ]:
dic_vocab = tokenizer.get_vocab()

In [ ]:
dic_index = {v:k for k, v in dic_vocab.items()}
dic_index

In [ ]:
dic_index[415]

'ë'

In [ ]:
import numpy as np
''.join([dic_index[i] for i in np.array(summary_ids[0])])

'</s><s>ì<unk><unk>ë<unk><unk>Ġ<unk><unk>Ġì<unk><unk>ì<unk><unk>Ġ</s>'

In [ ]:
text = tokenizer.decode(415)
text

'�'

In [ ]:
# summary_ids = model.generate(inputs['input_ids'], num_beams=4, max_length=5, early_stopping=True)
print([tokenizer.decode(g, skip_special_tokens=True, clean_up_tokenization_spaces=False) for g in summary_ids])

['��  �� ']


In [ ]:
inputs = tokenizer("안녕하세요 오늘 아침을 책임질 7시 기상 알람입니다. 저는 매일 7시에 알람이 맞춰져 있으며 사용자마다 커스텀이 가능합니다.", return_tensors="tf")
outputs = model(inputs)
outputs.decoder_hidden_states

In [ ]:
ARTICLE_TO_SUMMARIZE = "안녕하세요 오늘 아침을 책임질 7시 기상 알람입니다. 저는 매일 7시에 알람이 맞춰져 있으며 사용자마다 커스텀이 가능합니다."
inputs = tokenizer([ARTICLE_TO_SUMMARIZE], max_length=1024, return_tensors="tf")

# Generate Summary
summary_ids = model.generate(inputs["input_ids"], num_beams=4, max_length=5)
print(tokenizer.batch_decode(summary_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False))

['�']


ValueError: ignored

In [ ]:
last_hidden_states

In [ ]:
np.array(summary_ids[0]).squeeze()

array([  1,   0, 416,   5,   5, 415,   5,   5, 461,   5,   5, 461, 416,
         5,   5, 416,   5,   5, 461,   1], dtype=int32)

In [ ]:
import torch

text = """
1일 오후 9시까지 최소 20만3220명이 코로나19에 신규 확진됐다. 또다시 동시간대 최다 기록으로, 사상 처음 20만명대에 진입했다.
방역 당국과 서울시 등 각 지방자치단체에 따르면 이날 0시부터 오후 9시까지 전국 신규 확진자는 총 20만3220명으로 집계됐다.
국내 신규 확진자 수가 20만명대를 넘어선 것은 이번이 처음이다.
동시간대 최다 기록은 지난 23일 오후 9시 기준 16만1389명이었는데, 이를 무려 4만1831명이나 웃돌았다. 전날 같은 시간 기록한 13만3481명보다도 6만9739명 많다.
확진자 폭증은 3시간 전인 오후 6시 집계에서도 예견됐다.
오후 6시까지 최소 17만8603명이 신규 확진돼 동시간대 최다 기록(24일 13만8419명)을 갈아치운 데 이어 이미 직전 0시 기준 역대 최다 기록도 넘어섰다. 역대 최다 기록은 지난 23일 0시 기준 17만1451명이었다.
17개 지자체별로 보면 서울 4만6938명, 경기 6만7322명, 인천 1만985명 등 수도권이 12만5245명으로 전체의 61.6%를 차지했다. 서울과 경기는 모두 동시간대 기준 최다로, 처음으로 각각 4만명과 6만명을 넘어섰다.
비수도권에서는 7만7975명(38.3%)이 발생했다. 제주를 제외한 나머지 지역에서 모두 동시간대 최다를 새로 썼다.
부산 1만890명, 경남 9909명, 대구 6900명, 경북 6977명, 충남 5900명, 대전 5292명, 전북 5150명, 울산 5141명, 광주 5130명, 전남 4996명, 강원 4932명, 충북 3845명, 제주 1513명, 세종 1400명이다.
집계를 마감하는 자정까지 시간이 남아있는 만큼 2일 0시 기준으로 발표될 신규 확진자 수는 이보다 더 늘어날 수 있다. 이에 따라 최종 집계되는 확진자 수는 21만명 안팎을 기록할 수 있을 전망이다.
한편 전날 하루 선별진료소에서 이뤄진 검사는 70만8763건으로 검사 양성률은 40.5%다. 양성률이 40%를 넘은 것은 이번이 처음이다. 확산세가 계속 거세질 수 있다는 얘기다.
이날 0시 기준 신규 확진자는 13만8993명이었다. 이틀 연속 13만명대를 이어갔다.
"""

text = text.replace('\n', ' ')

raw_input_ids = tokenizer.encode(text)
input_ids = [tokenizer.bos_token_id] + raw_input_ids + [tokenizer.eos_token_id]

# summary_ids = model.generate(torch.tensor([input_ids]),  num_beams=4,  max_length=512,  eos_token_id=1)
d = tokenizer.decode(np.array(summary_ids[0]).squeeze().tolist(), skip_special_tokens=True)

In [ ]:
tokenizer.decode(np.array(summary_ids[0]).squeeze().tolist(), skip_special_tokens=True)

'��  �� '

In [ ]:
np.array(summary_ids[0]).squeeze().tolist()

[1, 0, 416, 5, 5, 415, 5, 5, 461, 5, 5, 461, 416, 5, 5, 416, 5, 5, 461, 1]

In [ ]:
ans = ''
for idx in np.array(summary_ids[0]).squeeze().tolist(): 
  ans += dic_index[idx]
ans

'</s><s>ì<unk><unk>ë<unk><unk>Ġ<unk><unk>Ġì<unk><unk>ì<unk><unk>Ġ</s>'

In [ ]:
decoded_value = d.encode()
decoded_value

b'\xef\xbf\xbd\xef\xbf\xbd  \xef\xbf\xbd\xef\xbf\xbd '

In [ ]:
decoded_value.decode('cp949')

'占쏙옙  占쏙옙 '

# 세 번째야

In [ ]:
# git clone
%cd /content/drive/MyDrive/mjjeon
!pwd
!git clone https://github.com/seujung/KoBART-summarization.git

/content/drive/MyDrive/mjjeon
/content/drive/MyDrive/mjjeon
Cloning into 'KoBART-summarization'...
remote: Enumerating objects: 142, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 142 (delta 46), reused 37 (delta 37), pack-reused 83
Receiving objects: 100% (142/142), 37.23 MiB | 20.55 MiB/s, done.
Resolving deltas: 100% (76/76), done.


In [ ]:
# save data to tsv file
import csv
from tqdm import tqdm

with open('/content/drive/MyDrive/mjjeon/KoBART-summarization/data/train.tsv', 'w', encoding='utf-8', newline='') as f:
    tw = csv.DictWriter(f, fieldnames = ["news", "summary"], delimiter='\t')
    tw.writeheader()
    for original, summary in zip(tqdm(df_train['original']), df_train['summary']):
        tw.writerow({'news': original.replace('\n', ' '), 'summary': summary.replace('\n', ' ')})


100%|██████████| 21600/21600 [00:01<00:00, 21595.31it/s]


In [ ]:
with open('/content/drive/MyDrive/mjjeon/KoBART-summarization/data/test.tsv', 'w', encoding='utf-8', newline='') as f:
    tw = csv.DictWriter(f, fieldnames = ["news", "summary"], delimiter='\t')
    tw.writeheader()
    for original, summary in zip(tqdm(df_test['original']), df_test['summary']):
        tw.writerow({'news': original.replace('\n', ' '), 'summary': summary.replace('\n', ' ')})


100%|██████████| 2700/2700 [00:00<00:00, 21708.82it/s]


In [ ]:
# train.py
!pwd

/content


In [ ]:
%cd /content/drive/MyDrive/mjjeon/KoBART-summarization

/content/drive/MyDrive/mjjeon/KoBART-summarization


In [ ]:
!pip install pytorch-lightning

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 800 kB 9.7 MB/s 
     |████████████████████████████████| 125 kB 83.9 MB/s 
     |████████████████████████████████| 512 kB 90.9 MB/s 


In [ ]:
!python train.py --gradient_clip_val 1.0  \
                 --max_epochs 50 \
                 --default_root_dir logs \
                 --gpus 1 \
                 --batch_size 8 \
                 --num_workers 4

You passed along `num_labels=3` with an incompatible id to label map: {'0': 'NEGATIVE', '1': 'POSITIVE'}. The number of labels wil be overwritten to 2.
INFO:root:Namespace(accelerator=None, accumulate_grad_batches=None, amp_backend='native', amp_level=None, auto_lr_find=False, auto_scale_batch_size=False, auto_select_gpus=False, batch_size=8, benchmark=None, check_val_every_n_epoch=1, checkpoint_path=None, default_root_dir='logs', detect_anomaly=False, deterministic=None, devices=None, enable_checkpointing=True, enable_model_summary=True, enable_progress_bar=True, fast_dev_run=False, gpus=1, gradient_clip_algorithm=None, gradient_clip_val=1.0, inference_mode=True, ipus=None, limit_predict_batches=None, limit_test_batches=None, limit_train_batches=None, limit_val_batches=None, log_every_n_steps=50, logger=True, lr=3e-05, max_epochs=50, max_len=512, max_steps=-1, max_time=None, min_epochs=None, min_steps=None, model_path=None, move_metrics_to_cpu=False, multiple_trainloader_mode='max_siz

In [ ]:
# memory footprint support libraries/code
!ln -sf /opt/bin/nvidia-smi /usr/bin/nvidia-smi
!pip install gputil
!pip install psutil
!pip install humanize

import psutil
import humanize
import os
import GPUtil as GPU

GPUs = GPU.getGPUs()
# XXX: only one GPU on Colab and isn’t guaranteed
gpu = GPUs[0]
def printm():
    process = psutil.Process(os.getpid())
    print("Gen RAM Free: " + humanize.naturalsize(psutil.virtual_memory().available), " |     Proc size: " + humanize.naturalsize(process.memory_info().rss))
    print("GPU RAM Free: {0:.0f}MB | Used: {1:.0f}MB | Util {2:3.0f}% | Total     {3:.0f}MB".format(gpu.memoryFree, gpu.memoryUsed, gpu.memoryUtil*100, gpu.memoryTotal))
printm()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for gputil: filename=GPUtil-1.4.0-py3-none-any.whl size=7409 sha256=64aefa8a3f6c687cb32192e71e292e9af6f3c0332e3ed7951ab6b00abde84003
  Stored in directory: /root/.cache/pip/wheels/ba/03/bb/7a97840eb54479b328672e15a536e49dc60da200fb21564d53
Successfully built gputil
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Gen RAM Free: 52.9 GB  |     Proc size: 223.6 MB
GPU RAM Free: 15109MB | Used: 0MB | Util   0% | Total     15109MB


# BERT SCORE


In [9]:
!pip install bert-score

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 60 kB 6.2 MB/s 
     |████████████████████████████████| 5.8 MB 34.5 MB/s 
     |████████████████████████████████| 182 kB 77.1 MB/s 
     |████████████████████████████████| 7.6 MB 57.7 MB/s 


In [5]:
!pip uninstall keras

Found existing installation: keras 2.9.0
Uninstalling keras-2.9.0:
  Would remove:
    /usr/local/lib/python3.8/dist-packages/keras-2.9.0.dist-info/*
    /usr/local/lib/python3.8/dist-packages/keras/*
Proceed (y/n)? Y
  Successfully uninstalled keras-2.9.0


In [6]:
!pip install keras==2.6.*

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.3 MB 21.2 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.9.2 requires keras<2.10.0,>=2.9.0rc0, but you have keras 2.6.0 which is incompatible.


In [1]:
!git clone https://github.com/Tiiiger/bert_score

Cloning into 'bert_score'...
remote: Enumerating objects: 982, done.
remote: Counting objects: 100% (344/344), done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 982 (delta 207), reused 308 (delta 180), pack-reused 638
Receiving objects: 100% (982/982), 1.35 MiB | 8.38 MiB/s, done.
Resolving deltas: 100% (522/522), done.


In [7]:
%cd /content/bert_score

/content/bert_score


In [3]:
y_true = "노형욱 국토교통부 장관은 7월 14일 수도권 코로나19 방역의 관문이라고 할 수 있는 서울역을 방문하여, 철도역사 및 열차 방역실태 등을 점검하고, 관계자들을 격려하였다. 또한 방역으로 인해 자칫 운행 안전에 대한 경각심이 느슨해질 수 있다면서, 촘촘하고 치밀한 시설물 점검 및 차량의 정비를 통해 안전사고 예방에도 만전을 기해줄 것을 당부하였다."
y_pred = '노 장관은 서울역을 방문하여 철도역사 및 열차 방역실태 등을 점검하고 관계자들을 격려하였다.'

In [8]:
!bert-score -r example/refs2.txt -c example/hyps.txt --lang others

/bin/bash: bert-score: command not found


In [20]:
!bert-score -r example/refs2.txt -c example/hyps.txt --lang others

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
bert-base-multilingual-cased_L9_no-idf_version=0.3.12(hug_trans=4.25.1)_fast-tokenizer P: 0.777701 R: 0.762030 F1: 0.769786


In [11]:
from bert_score import score

refs = ["노형욱 국토교통부 장관은 7월 14일 수도권 코로나19 방역의 관문이라고 할 수 있는 서울역을 방문하여, 철도역사 및 열차 방역실태 등을 점검하고, 관계자들을 격려하였다. 또한 방역으로 인해 자칫 운행 안전에 대한 경각심이 느슨해질 수 있다면서, 촘촘하고 치밀한 시설물 점검 및 차량의 정비를 통해 안전사고 예방에도 만전을 기해줄 것을 당부하였다."]
cands = ['노 장관은 서울역을 방문하여 철도역사 및 열차 방역실태 등을 점검하고 관계자들을 격려하였다.']

(P, R, F), hashname = score(cands, refs, lang="others", return_hash=True)
print(
    f"{hashname}: P={P.mean().item():.6f} R={R.mean().item():.6f} F={F.mean().item():.6f}"
)

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/996k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/714M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


bert-base-multilingual-cased_L9_no-idf_version=0.3.12(hug_trans=4.25.1): P=0.915823 R=0.737988 F=0.817345


In [14]:
import bert_score

AlreadyExistsError: ignored

In [12]:
import torch

!pip install keras-nlp --upgrade

!pip install rouge-score --upgrade


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 337 kB 12.5 MB/s 
     |████████████████████████████████| 5.8 MB 60.1 MB/s 
     |████████████████████████████████| 588.3 MB 22 kB/s 
INFO: pip is looking at multiple versions of tensorflow-text to determine which version is compatible with other requirements. This could take a while.
     |████████████████████████████████| 5.9 MB 51.0 MB/s 
     |████████████████████████████████| 578.1 MB 8.7 kB/s 
     |████████████████████████████████| 578.1 MB 7.1 kB/s 
     |████████████████████████████████| 4.6 MB 57.3 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24955 sha256=fa5680f280bf77145ad227fc8c2188c40a47df2f101c531f145a16595a33c1eb
  Stored in directory: /root/.cache/pip/wheels/24/55/6f/ebfc4cb176d1c9665da4e306e1

In [13]:

from tensorflow import keras
import rouge_score
import keras_nlp
from keras_nlp.metrics.rouge_base import RougeBase
rouge_l = keras_nlp.metrics.RougeL()
y_true = "노형욱 국토교통부 장관은 7월 14일 수도권 코로나19 방역의 관문이라고 할 수 있는 서울역을 방문하여, 철도역사 및 열차 방역실태 등을 점검하고, 관계자들을 격려하였다. 또한 방역으로 인해 자칫 운행 안전에 대한 경각심이 느슨해질 수 있다면서, 촘촘하고 치밀한 시설물 점검 및 차량의 정비를 통해 안전사고 예방에도 만전을 기해줄 것을 당부하였다."
y_pred = '노 장관은 서울역을 방문하여 철도역사 및 열차 방역실태 등을 점검하고 관계자들을 격려하였다.'
rouge_l(y_true, y_pred)

{'precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 'recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 'f1_score': <tf.Tensor: shape=(), dtype=float32, numpy=0.0>}